name: Main

# This specifies when the workflow should run.
on:
  push:
    branches: [main] # Triggers the workflow on push events to the main branch.
  workflow_dispatch: # Allows the workflow to be manually triggered.

# This section ensures that only one workflow runs at a time per branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Removed the 'verify' job.

  # This job handles the versioning and changelog generation using Changesets.
  changesets:
    name: Changesets
    runs-on: ubuntu-latest # Specifies the type of runner that the job will run on.
    timeout-minutes: 5 # Specifies the maximum runtime before the job is canceled.

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags, needed for changelog generation.

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # Specifies the Node.js version to use.
          # cache: "pnpm" # Caches dependencies using pnpm's caching mechanism.

      - name: Install pnpm
        run: npm install -g pnpm
        
      - name: Install dependencies
        run: pnpm install # Installs dependencies using pnpm.

      - name: Create Version Pull Request
        uses: changesets/action@v1
        with:
          version: pnpm run changeset:version # Uses pnpm to run the version script from Changesets.
          commit: "chore: version package"
          title: "Version Packages" # The title for the pull request created by Changesets.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # This job handles the publishing of packages to NPM.
  release:
    name: Release
    needs: changesets # Specifies that this job needs the 'changesets' job to complete successfully before it starts.
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          # cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # - name: Build packages
      #   run: pnpm run build
        # This command should run the build script defined in your package.json.
        # You can adjust the command to target specific packages if needed.

      - name: Publish to NPM
        uses: changesets/action@v1
        with:
          publish: pnpm run changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}